import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import { ThemeToggle } from '@/components/theme-toggle'
import { AppContextProvider } from '@/components/app-context'
import MainNav from '@/components/main-nav'
import { Toaster } from '@/components/ui/toaster'
import { ToastDrawer } from '@/components/ui/toast-drawer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'shadcn/ui demo',
  description: 'Generated by create next app',
}

// export const metadata: Metadata = {
//   title: {
//     default: siteConfig.name,
//     template: `%s - ${siteConfig.name}`,
//   },
//   description: siteConfig.description,
//   themeColor: [
//     { media: "(prefers-color-scheme: light)", color: "white" },
//     { media: "(prefers-color-scheme: dark)", color: "black" },
//   ],
//   icons: {
//     icon: "/favicon.ico",
//     shortcut: "/favicon-16x16.png",
//     apple: "/apple-touch-icon.png",
//   },
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-gradient-to-br from-indigo-100 via-slate-50 to-purple-100 dark:from-indigo-950 dark:via-slate-900 dark:to-purple-950",
          inter.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AppContextProvider>
            {/* <MainNav /> */}
            <ThemeToggle />
            <hr />
            {children}
            {/* <Toaster /> */}
            {/* <ToastDrawer /> */}
          </AppContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
